---
title: "Reproducible Research: Peer Assessment 1"
author: "R. Hosek"
date: "November 13, 2015"
output: html_document
---
## Loading and preprocessing the data. 
###This dataset covers acitivity over 61 days from Oct 1 through Nov 30. We will refer to the days serially, i.e., day 1, day 2, ... day 61 .Each day consists of 288 5-minute intervals: 0-5, 5-10, ... 1435-1440. We will refer to the intervals serially also: int 1, int 2, ... int 288. We first load the unzipped dataset from the working directory and then add a date field.

```{R}
activ <- read.csv("activity.csv")

library(plyr)
activ_2 <- mutate(activ, date_2 = as.Date(as.character(activ$date)))

 v1 <- c(0)
 
for(i in 2:61){
  v1 <- c(v1, sum(activ_2$steps[activ_2$date_2 == as.Date(as.character(levels(activ_2$date)[i]))], na.rm=T))}

activ_3 <- data.frame(levels(activ_2$date), v1)
```

## Ignoring missing data, what is mean total number of steps taken per day?

```{R}
activ_3$v1
meanSteps <- mean(activ_3$v1, na.rm=T)
medianSteps <- median(activ_3$v1, na.rm=T)

```
###The mean total steps taken per day = ```r as.integer(meanSteps)```.
###The median total steps = '``r as.integer(medianSteps)``'.

###Below is the HISTOGRAM which was requested in the assignment
```{r}

hist(activ_3$v, main="Histogram of Step Frequency", breaks=24,  xlab="Step Intervals", ylab="Frequency")

```



###Below is a barplot showing total steps by day with the mean (red) and median (blue)lines superimposed
 This was not requested in the assignment but is useful for illustratating mean and median
 
```{R}
barplot(activ_3$v, names.arg=c(1:61),main="Total Step per day (mean in red, median in blue)", xlab="Day", ylab="Total Steps")
abline(h=mean(activ_3$v), col="red")
abline(h=median(activ_3$v), col="blue")
```

## What is the average daily activity pattern?
###Modify original dataframe to add interval numbers and then create vector of iterval averages to plot; ignore NAs
```{R}
 intervalCnt <- rep(c(1:288), 61)
activ_4 <- cbind(activ_2, intervalCnt)
intervalAvgs <- c()
for (i in 1:288){
 intervalAvgs <- c(intervalAvgs, mean(activ_4$steps[activ_4$intervalCnt==i], na.rm=T))
}
intDF <- data.frame(1:288, intervalAvgs)
names(intDF)[1]<-"Interval"

plot( intDF$intervalAvgs, type="l", main="Average Steps by Interval", xlab="Interval Number", ylab="Average Steps")
maxInterval <- which.max(intDF$intervalAvgs)


```
###The  max value is ```r as.integer(max(intDF$intervalAvgs))```. 
###Which occurs in interval ```r maxInterval``` which corresponds to 8:35-8:40 am.

## Imputing missing values
###We first find the number of rows with NA's and then modify the dataframe to add dayOfWeek, factor it and order factors
```{R}
No_Of_NAs<-length(activ_2$steps[(is.na(activ_2$steps))])

```
###The number of rows containing NAs is '``r No_Of_NAs``'.
###We will now find the day-of-week average, ignoring NA's, and use it to replace the NA's by day-of-week

```{R}
activ_5 <- mutate(activ_2, dayOfWeek = weekdays(as.Date(as.Date(as.character(activ_2[,4])),'%y-%m-%d')) )
activ_5$O_dayOfweek <- with(data=activ_5, 
  ifelse ((dayOfWeek == "Monday"),1, 
  ifelse ((dayOfWeek == "Tuesday"),2, 
  ifelse ((dayOfWeek == "Wednesday"),3, 
  ifelse ((dayOfWeek == "Thursday"),4, 
  ifelse ((dayOfWeek == "Friday"),5, 
  ifelse ((dayOfWeek == "Saturday"),6,7))))))) 
activ_5$O_dayOfweek <- factor(activ_5$O_dayOfweek, 
levels=1:7, 
labels=c("Mon", "Tue", "Wed", "Thur", "Fri", "Sat", "Sun")) 

  avgval <- c()
  avgval <- c(avgval, mean(activ_5$steps[levels(activ_5$O_dayOfweek)=="Mon"], na.rm=T))
  avgval <- c(avgval, mean(activ_5$steps[levels(activ_5$O_dayOfweek)=="Tue"], na.rm=T))
  avgval <- c(avgval, mean(activ_5$steps[levels(activ_5$O_dayOfweek)=="Wed"], na.rm=T))
  avgval <- c(avgval, mean(activ_5$steps[levels(activ_5$O_dayOfweek)=="Thur"], na.rm=T))
  avgval <- c(avgval, mean(activ_5$steps[levels(activ_5$O_dayOfweek)=="Fri"], na.rm=T))
  avgval <- c(avgval, mean(activ_5$steps[levels(activ_5$O_dayOfweek)=="Sat"], na.rm=T))
  avgval <- c(avgval, mean(activ_5$steps[levels(activ_5$O_dayOfweek)=="Sun"], na.rm=T))

avgval <- as.integer(avgval)


activ_5$steps[levels(activ_5$O_dayOfweek)=="Mon"]  <- replace(activ_5$steps[levels(activ_5$O_dayOfweek)=="Mon"], is.na(activ_5$steps[levels(activ_5$O_dayOfweek)=="Mon"]), avgval[1])

activ_5$steps[levels(activ_5$O_dayOfweek)=="Tue"]  <- replace(activ_5$steps[levels(activ_5$O_dayOfweek)=="Tue"], is.na(activ_5$steps[levels(activ_5$O_dayOfweek)=="Tue"]), avgval[2])

activ_5$steps[levels(activ_5$O_dayOfweek)=="Wed"]  <- replace(activ_5$steps[levels(activ_5$O_dayOfweek)=="Wed"], is.na(activ_5$steps[levels(activ_5$O_dayOfweek)=="Wed"]), avgval[3])

activ_5$steps[levels(activ_5$O_dayOfweek)=="Thur"]  <- replace(activ_5$steps[levels(activ_5$O_dayOfweek)=="Thur"], is.na(activ_5$steps[levels(activ_5$O_dayOfweek)=="Thur"]), avgval[4])

activ_5$steps[levels(activ_5$O_dayOfweek)=="Fri"]  <- replace(activ_5$steps[levels(activ_5$O_dayOfweek)=="Fri"], is.na(activ_5$steps[levels(activ_5$O_dayOfweek)=="Fri"]), avgval[5])

activ_5$steps[levels(activ_5$O_dayOfweek)=="Sat"]  <- replace(activ_5$steps[levels(activ_5$O_dayOfweek)=="Sat"], is.na(activ_5$steps[levels(activ_5$O_dayOfweek)=="Sat"]), avgval[6])

activ_5$steps[levels(activ_5$O_dayOfweek)=="Sun"]  <- replace(activ_5$steps[levels(activ_5$O_dayOfweek)=="Sun"], is.na(activ_5$steps[levels(activ_5$O_dayOfweek)=="Sun"]), avgval[7])


activ_5$weekday<-factor(ifelse(activ_5$dayOfWeek%in%c('Saturday','Sunday'),'weekend','weekday'))
activ_5 <- cbind(activ_5, intervalCnt)


v2 <- c(0)
 
for(i in 2:61){
  v2 <- c(v2, sum(activ_5$steps[activ_5$date_2 == as.Date(as.character(levels(activ_2$date)[i]))], na.rm=T))}

activ_6 <- data.frame(levels(activ_5$date), v2)

meanSteps1 <- mean(activ_6$v2, na.rm=T)
medianSteps1 <- median(activ_6$v2, na.rm=T)

hist(activ_6$v2, main="Histogram of Step Frequency - modified dataset", breaks = 24, xlab="Step Intervals", ylab="Frequency")

```

###The mean total steps taken per day = ```r as.integer(meanSteps1)```
###The median = '``r as.integer(medianSteps1)``'.


### Are there differences in activity patterns between weekdays and weekends?

```{R}

dfWeekday <- subset(activ_5, activ_5$weekday == 'weekday')

dfWeekend <- subset(activ_5, activ_5$weekday == 'weekend')
par(mfrow=c(2,1),  oma = c(5,4,0,0) + 0.1,
          mar = c(1,0,1,1) + 0.1)

intervalAvgs <- c()
for (i in 1:288){
 intervalAvgs <- c(intervalAvgs, mean(dfWeekday$steps[dfWeekday$intervalCnt==i], na.rm=T))
}
intDFWeekday <- data.frame(1:288, intervalAvgs)
names(intDFWeekday)[1]<-"Interval"

intervalAvgs <- c()
for (i in 1:288){
 intervalAvgs <- c(intervalAvgs, mean(dfWeekend$steps[dfWeekend$intervalCnt==i], na.rm=T))
}
intDFWeekend <- data.frame(1:288, intervalAvgs)
names(intDFWeekend)[1]<-"Interval"

plot( intDFWeekday$intervalAvgs, type="l",  ylab="Average Steps", xlab="", main = "Average Steps per Interval for Weekdays (top) and weekends")

plot( intDFWeekend$intervalAvgs, type="l",  xlab="Interval Number", ylab="Average Steps", )

```


###The activity patterns between weekdays and weekends are definitely different.


